# Site settings
title: From Coding Novice to Web Developer
header-img: img/home-bg.png
email: bklyngal1994@gmail.com
copyright_name: Eclecticdynasty
description: > # this means to ignore newlines until "baseurl:"
  Pursuing my passion
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: SiobhanAMartin
github_username:  Eclecticdynasty
learn_profile: Eclecticdynasty
email_username: bklyngal1994@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
